# Generated by Django 2.2.6 on 2020-01-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
        ('bhawan_app', '0003_hostelfacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_relation', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'hostel visitor',
            },
        ),
        migrations.CreateModel(
            name='HostelRoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('time_of_booking', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('number_of_rooms', models.PositiveIntegerField(max_length=2)),
                ('booking_status', models.CharField(max_length=255)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_RESIDENCE_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_PERSON_MODEL)),
                ('visitor_details', models.ManyToManyField(to='bhawan_app.HostelVisitor')),
            ],
            options={
                'verbose_name_plural': 'hostel room booking',
                'ordering': ['-time_of_booking'],
            },
        ),
    ]
