# Generated by Django 2.2.6 on 2020-01-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0004_hostelroombooking_hostelvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelroombooking',
            name='number_of_rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
