# Generated by Django 4.1.5 on 2024-04-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0016_auto_20221116_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_students',
            field=models.ManyToManyField(related_name='registered_events', to='bhawan_app.resident'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('res', 'Resolved'), ('pen', 'Pending'), ('unr', 'Unresolved'), ('ipr', 'Inprocess')], default='pen', max_length=10),
        ),
    ]
