# Generated by Django 4.1.5 on 2024-04-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0018_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deadline_date',
            field=models.DateField(default='2003-11-23'),
            preserve_default=False,
        ),
    ]
