# Generated by Django 4.1.5 on 2024-04-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0018_event_deadline_date_event_location'),
        ('bhawan_app', '0019_event_deadline_date'),
    ]

    operations = [
    ]
