# Generated by Django 4.1.5 on 2026-04-12 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
        ('bhawan_app', '0020_remove_resident_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonResidingStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('ra', 'RA'), ('pdf', 'PDF'), ('jrf', 'JRF'), ('srf', 'SRF'), ('project_fellow', 'Project Fellow'), ('npdf', 'NPDF'), ('ipdf', 'IPDF'), ('research_intern', 'Research Intern'), ('visitor', 'Visitor')], max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('upto_date', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_RESIDENCE_MODEL)),
            ],
            options={
                'ordering': ['-from_date', '-datetime_created'],
            },
        ),
    ]
