# Generated by Django 4.1.5 on 2026-04-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0021_nonresidingstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonresidingstudent',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
