# Generated by Django 4.1.5 on 2026-04-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0022_alter_nonresidingstudent_department'),
        ('bhawan_app', '0022_alter_nonresidingstudent_id'),
    ]

    operations = [
    ]
