# Generated by Django 4.1.5 on 2026-04-11 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0022_alter_nonresidingstudent_department'),
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nonresidingstudent',
            name='staying_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_residing_staying_students', to=settings.KERNEL_RESIDENCE_MODEL),
        ),
    ]
