# Generated by Django 4.1.5 on 2026-04-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0023_merge_20260411_1613'),
        ('bhawan_app', '0023_nonresidingstudent_staying_hostel'),
    ]

    operations = [
    ]
